// <auto-generated />
using System;
using IOTCashReader.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IOTCashReader.Migrations
{
    [DbContext(typeof(ModelsContext))]
    [Migration("20190815095647_usertableupdate")]
    partial class usertableupdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IOTCashReader.Models.Credit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime");

                    b.Property<double>("Value");

                    b.HasKey("Id");

                    b.ToTable("Credits");
                });

            modelBuilder.Entity("IOTCashReader.Models.Safe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SafeName");

                    b.Property<string>("SerialNumber");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasFilter("[SerialNumber] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Safe");
                });

            modelBuilder.Entity("IOTCashReader.Models.SafeCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreditId");

                    b.Property<int?>("SafeId");

                    b.HasKey("Id");

                    b.HasIndex("CreditId");

                    b.HasIndex("SafeId");

                    b.ToTable("SafeCredit");
                });

            modelBuilder.Entity("IOTCashReader.Models.SafeWithdrawal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SafeId");

                    b.Property<int?>("WithdrawalId");

                    b.HasKey("Id");

                    b.HasIndex("SafeId");

                    b.HasIndex("WithdrawalId");

                    b.ToTable("SafeWithdrawal");
                });

            modelBuilder.Entity("IOTCashReader.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("User");
                });

            modelBuilder.Entity("IOTCashReader.Models.Withdrawal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime");

                    b.Property<double>("Value");

                    b.HasKey("Id");

                    b.ToTable("Withdrawal");
                });

            modelBuilder.Entity("IOTCashReader.Models.Safe", b =>
                {
                    b.HasOne("IOTCashReader.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("IOTCashReader.Models.SafeCredit", b =>
                {
                    b.HasOne("IOTCashReader.Models.Credit", "Credit")
                        .WithMany()
                        .HasForeignKey("CreditId");

                    b.HasOne("IOTCashReader.Models.Safe", "Safe")
                        .WithMany()
                        .HasForeignKey("SafeId");
                });

            modelBuilder.Entity("IOTCashReader.Models.SafeWithdrawal", b =>
                {
                    b.HasOne("IOTCashReader.Models.Safe", "Safe")
                        .WithMany()
                        .HasForeignKey("SafeId");

                    b.HasOne("IOTCashReader.Models.Withdrawal", "Withdrawal")
                        .WithMany()
                        .HasForeignKey("WithdrawalId");
                });
#pragma warning restore 612, 618
        }
    }
}
